export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-16 space-y-8">
        <div>
          <h1 className="text-3xl font-bold">Terms of Service</h1>
          <p className="text-muted-foreground mt-2">Last updated: March 2025</p>
        </div>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            By using Orianna, you agree to these Terms of Service. If you do not agree, please do not use the platform.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">2. Description of Service</h2>
          <p className="text-muted-foreground leading-relaxed">
            Orianna is an AI-powered content coaching platform that helps creators plan, script, and schedule video content
            for TikTok and Instagram. We use artificial intelligence to assist with content ideation and
            scripting, and integrate with social media platforms to publish content on your behalf.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">3. User Responsibilities</h2>
          <ul className="text-muted-foreground space-y-2 list-disc list-inside leading-relaxed">
            <li>You are responsible for all content you create and publish through our platform</li>
            <li>You must comply with the terms of service of each social media platform you connect</li>
            <li>You must not use the platform to publish spam, misinformation, or content that violates platform guidelines</li>
            <li>You are responsible for maintaining the security of your account credentials</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">4. Social Media Integration</h2>
          <p className="text-muted-foreground leading-relaxed">
            When you connect a social media account, you authorize Orianna to publish content to that platform on your behalf.
            You may revoke this authorization at any time by disconnecting the account in Settings.
            We are not responsible for changes to third-party platform APIs or policies that may affect our ability to publish content.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">5. AI-Generated Content</h2>
          <p className="text-muted-foreground leading-relaxed">
            Scripts and content suggestions generated by our AI are provided as assistance tools.
            You retain full responsibility for reviewing, editing, and approving any AI-generated content before publishing.
            We make no guarantees about the accuracy, originality, or performance of AI-generated content.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">6. Intellectual Property</h2>
          <p className="text-muted-foreground leading-relaxed">
            You retain ownership of all content you create. By using our service, you grant us a limited license to
            process and temporarily store your content for the purpose of providing our services.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">7. Limitation of Liability</h2>
          <p className="text-muted-foreground leading-relaxed">
            Orianna is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from
            your use of the platform, including but not limited to failed posts, content rejection by platforms,
            or loss of data. Use of AI-generated content is at your own risk.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">8. Changes to Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            We may update these terms from time to time. Continued use of the platform after changes constitutes acceptance.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">9. Contact</h2>
          <p className="text-muted-foreground leading-relaxed">
            For questions about these terms, please contact us through the app.
          </p>
        </section>
      </div>
    </div>
  )
}
